#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-pdm
Version  : 2.7.4
Release  : 3
URL      : https://files.pythonhosted.org/packages/b0/6a/63263a1c32fcf9ea1b004b594580400d3af113b593ae8966f92539809994/pdm-2.7.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/b0/6a/63263a1c32fcf9ea1b004b594580400d3af113b593ae8966f92539809994/pdm-2.7.4.tar.gz
Summary  : A modern Python package and dependency manager supporting the latest PEP standards
Group    : Development/Tools
License  : MIT
Requires: pypi-pdm-bin = %{version}-%{release}
Requires: pypi-pdm-license = %{version}-%{release}
Requires: pypi-pdm-python = %{version}-%{release}
Requires: pypi-pdm-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(pdm_backend)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<div align="center">
# PDM
A modern Python package and dependency manager supporting the latest PEP standards.

%package bin
Summary: bin components for the pypi-pdm package.
Group: Binaries
Requires: pypi-pdm-license = %{version}-%{release}

%description bin
bin components for the pypi-pdm package.


%package license
Summary: license components for the pypi-pdm package.
Group: Default

%description license
license components for the pypi-pdm package.


%package python
Summary: python components for the pypi-pdm package.
Group: Default
Requires: pypi-pdm-python3 = %{version}-%{release}

%description python
python components for the pypi-pdm package.


%package python3
Summary: python3 components for the pypi-pdm package.
Group: Default
Requires: python3-core
Provides: pypi(pdm)
Requires: pypi(blinker)
Requires: pypi(cachecontrol)
Requires: pypi(certifi)
Requires: pypi(findpython)
Requires: pypi(installer)
Requires: pypi(packaging)
Requires: pypi(platformdirs)
Requires: pypi(pyproject_hooks)
Requires: pypi(python_dotenv)
Requires: pypi(requests_toolbelt)
Requires: pypi(resolvelib)
Requires: pypi(rich)
Requires: pypi(shellingham)
Requires: pypi(tomlkit)
Requires: pypi(unearth)
Requires: pypi(virtualenv)

%description python3
python3 components for the pypi-pdm package.


%prep
%setup -q -n pdm-2.7.4
cd %{_builddir}/pdm-2.7.4
pushd ..
cp -a pdm-2.7.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1687797170
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pdm
cp %{_builddir}/pdm-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pdm/a6332fcb27ade3ff14f6cb6e8db45cb6ef3542f2 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pdm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pdm/a6332fcb27ade3ff14f6cb6e8db45cb6ef3542f2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
